dataset:
  name: porto
  trajectory_file: data/porto/trajectories.txt
  output_dir: outputs/fairtraj_core

spatial:
  bounds:
    lati_min: 41.111975
    long_min: -8.667057
    lati_max: 41.177462
    long_max: -8.585305
  quadtree_capacity: 6000
  kde_search_radius_m: 3000

dwgat:
  in_channels: 2
  hidden_channels: 128
  out_channels: 1
  heads: 3
  num_layers: 3
  epochs: 3000
  learning_rate: 0.002

diffusion:
  in_channels: 2
  out_channels: 2
  ch: 128
  cond_ch: 128
  ch_mult: [1, 2, 2, 2]
  num_res_blocks: 2
  dropout: 0.1
  beta_start: 0.0001
  beta_end: 0.05
  num_diffusion_timesteps: 500
